FROM ubuntu:24.04

# Install build tools and OpenSSL
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev

# Copy source files
COPY . /app
WORKDIR /app

# Compile with OpenSSL (-lcrypto)
RUN gcc -o encrypter encrypter.c linked_list.c mta_crypt.c mta_rand.c -lpthread -lcrypto

# Run the executable
CMD ["./encrypter"]
